spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.164.223:3306/mybatis
    username: root
    password: 111111
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8081

zxxxd:
  hello:
    prefix: hello
    suffix: world