spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.3.37.155:1521:orcl
    username: herendh
    password: herendh
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
