server:
  port: 3344
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zxxxd1001/cloud-config.git
#          search-paths: config-repo
#          username:   #账号密码写真实的快一些我觉得，不使用也能访问有点慢
#          password:  #密码